### ISSUE TITLE
練習CH1 專案時，依步驟在Poetry 中add lanchain 失敗

### ISSUE THREAD

**Issue by mapaul3511** [iangithub/LangChainLearnBook#1]
練習CH1 專案時，依步驟在Poetry 中add lanchain，在安裝numpy 套件時會報錯
Python 版本: 3.13.0
Poetry 版本: 1.8.4
Poetry Config:
cache-dir = "C:\\Users\\mapau.ACER-NITRO5\\AppData\\Local\\pypoetry\\Cache"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\mapau.ACER-NITRO5\AppData\Local\pypoetry\Cache\virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true

![image](https://github.com/user-attachments/assets/65c008d8-0d59-4e70-b968-1cb2467a8c41)
![image](https://github.com/user-attachments/assets/eaeb7dc6-134a-4d1c-bf6e-815328e28fda)

**Comment by Ko-Ko-Kirk** [comment]
從log來看，似乎你的電腦上沒有 C Compiler，可以安裝他建議的 [Microsoft Visual Studio Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/) 後再試試看

**Comment by mapaul3511** [comment]
@Ko-Ko-Kirk 從您提供的連結下載C++ Build Tool 安裝後，再執行poetry add langchain，numpy 的安裝問題就解決了，非常感謝！
