### ISSUE TITLE
ChatPromptTemplate用法確認

### ISSUE THREAD

**Issue by jimliu-newbd** [iangithub/LangChainLearnBook#3]
官方url:
[https://python.langchain.com/api_reference/core/prompts/langchain_core.prompts.chat.ChatPromptTemplate.html](url)

該函數用到的是`system`, `human`, `ai`

但書中的範例程式碼使用 `user`
https://github.com/iangithub/LangChainLearnBook/blob/f7bff80f7eaa52f86270f55bb189225aead34fe5/CH5/demo1/demo1/demo5-1.py#L21

請問這會影響結果嗎?

**Comment by iangithub** [comment]
根據 langchain 原始碼，human與user是相容的，langchain 原始碼如下

if message_type in ("human", "user"):
        message: BaseMessagePromptTemplate = HumanMessagePromptTemplate.from_template(
            template, template_format=template_format
        )
    elif message_type in ("ai", "assistant"):
        message = AIMessagePromptTemplate.from_template(
            cast(str, template), template_format=template_format
        )
    elif message_type == "system":
        message = SystemMessagePromptTemplate.from_template(
            cast(str, template), template_format=template_format
        )
