### ISSUE TITLE
RunnableLambda疑問

### ISSUE THREAD

**Issue by jimliu-newbd** [iangithub/LangChainLearnBook#4]
[https://github.com/iangithub/LangChainLearnBook/blob/f7bff80f7eaa52f86270f55bb189225aead34fe5/CH5/demo1/demo1/demo5-5.py#L53](url)

raw code:
```
workflow = RunnableSequence(
    validate_order, # why don't use Runnable object?
    prepare_llm_input_RunnableLambda,
    summary_chain,
    StrOutputParser()
)
```

1. 不懂為什麼 line 53不用 validate_order_RunnableLambda，但一樣可以執行。
2. 另外我也有嘗試放 RunnableSequence(validate_order_RunnableLambda, prepare_llm_input_RunnableLambda, ... ) 與RunnableSequence(validate_order, prepare_llm_input, ... ) 一樣都可以執行，出來的結果也都大同小異

綜合以上兩點，那這例子還有包成 Runnable object的必要嗎?

**Comment by iangithub** [comment]
第33行
使用 RunnableLambda 將普通的 Python 函數轉換為 Langchain 的 Runnable 物件，
如此一來可以與其他 Langchain 的組件（如 LLM、Prompt Templates）串接在一起


第53行
workflow = RunnableSequence(
    validate_order,
    prepare_llm_input_RunnableLambda,
    summary_chain,
    StrOutputParser()
)
與
workflow = RunnableSequence(
    validate_order_RunnableLambda,
    prepare_llm_input_RunnableLambda,
    summary_chain,
    StrOutputParser()
)

呈現的結果一樣是因為 RunnableSequence 內部會自動將普通函數轉換為 Runnable

而範例中的程式碼確實也是筆誤，原本應該是要寫成
workflow = RunnableSequence(
    validate_order_RunnableLambda,
    prepare_llm_input_RunnableLambda,
    summary_chain,
    StrOutputParser()
)


需不需要轉成Runnable object，則要看你的使用情境，如果函數需要在其他場景使用或需要更多 Runnable 功能時，會建議使用 RunnableLambda 轉成  Runnable 物件
