### ISSUE TITLE
Client error '429 Too Many Requests'

### ISSUE THREAD

**Issue by winhealthsteven** [iangithub/LangChainLearnBook#5]
scenario_array = [
    "在餐廳",
    "在學校",
]
vocabularies = [
    "hungry",
]

results = []

for vocabulary in vocabularies:
    for scenario in scenario_array:
        result = chain.invoke(
            {
                "native_language": native_language,
                "scenario": scenario,
                "target_language": target_language,
                "text": vocabulary,
            }
        )
        results.append(result)
        
請問 :  這邊才請求兩次，為何會出現'429 Too Many Requests'?
我的速率限制每分鐘可以發送6次

**Comment by iangithub** [comment]
這部份你必須去查你所使用的雲端平台，非程式端能控制的
