### ISSUE TITLE
書中的CH9首頁下方的章節介紹不對稱

### ISSUE THREAD

**Issue by jimliu-newbd** [iangithub/LangChainLearnBook#6]
CH9的內容為 langchain與huggingface的使用，但首頁下方在解釋langchain memory。

**Comment by iangithub** [comment]
感謝您的回饋，內容確實誤植了前一本著作的簡介，若有機會再刷，會修正。

**Comment by iangithub** [comment]
本章將帶您了解 Hugging Face 和 LangChain 的整合應用。包含介紹 Hugging Face 平台的背景，並引導您完成 Hugging Face 帳號的註冊。接著介紹如何利用 LangChain 的 Hugging Face 套件輕鬆整合開源的大語言模型，實現創新應用。
