### ISSUE TITLE
ch6 rag_with_history

### ISSUE THREAD

**Issue by winhealthsteven** [iangithub/LangChainLearnBook#8]
loader = WebBaseLoader("https://www.drmaster.com.tw/bookinfo.asp?BookID=MP22359")

docs = loader.load()

text_splitter = RecursiveCharacterTextSplitter()
documents = text_splitter.split_documents(docs)

qdrant = Qdrant.from_documents(
    docs,
    embeddings_model,
    url=qdrant_url, 
    api_key=qdrant_api_key,
    collection_name="book",
    force_recreate=True,
)

這裡應該要放documents，而不是docs?

**Comment by Ko-Ko-Kirk** [comment]
沒錯，你是對的，感謝指正🙏🙏

**Comment by iangithub** [comment]
已修正Sample Code
